/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import db.MongoHelper;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.DefaultListModel;
import model.Candidate;
import model.User;

/**
 *
 * @author YusufDS
 */
public class VotingFrame extends javax.swing.JFrame {

    /**
     * Creates new form VotingFrame
     */
    private User currentUser;
    private DefaultListModel<String> candidateModel = new DefaultListModel<>();
    private ResourceBundle bundle;

    public VotingFrame() {
        initComponents();
    }

    public VotingFrame(User user) {
        this.currentUser = user;
        initComponents();
        setLocationRelativeTo(null);

        loadCandidates();
        loadLanguageOptions();
        applyTranslations(); // default
    }

    private void loadCandidates() {
        candidateModel.clear();
        List<Candidate> candidates = MongoHelper.getAllCandidates();
        for (Candidate c : candidates) {
            candidateModel.addElement(c.getName());
        }
        listCandidates.setModel(candidateModel);
    }

    private void loadLanguageOptions() {
        cbLanguage.removeAllItems();
        cbLanguage.addItem("English");
        cbLanguage.addItem("Indonesia");

        cbLanguage.addActionListener(e -> applyTranslations());
    }

    private void applyTranslations() {
        String lang = cbLanguage.getSelectedItem().toString();
        Locale locale = lang.equals("Indonesia") ? new Locale("id") : new Locale("en");

        bundle = ResourceBundle.getBundle("i18n.messages", locale);
        setTitle(bundle.getString("voting.title"));
        btnVote.setText(bundle.getString("label.select_candidate"));
        lblStatus.setText(""); // kosongin status
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listCandidates = new javax.swing.JList<>();
        cbLanguage = new javax.swing.JComboBox<>();
        btnVote = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        listCandidates.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listCandidates);

        cbLanguage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indonesia", "English" }));

        btnVote.setText("Vote");
        btnVote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoteActionPerformed(evt);
            }
        });

        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cbLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(btnVote)))
                        .addGap(107, 107, 107))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnVote)
                        .addGap(0, 36, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoteActionPerformed
        String selected = listCandidates.getSelectedValue();
        if (selected == null) {
            lblStatus.setText(bundle.getString("label.select_candidate"));
            return;
        }

        // Update kandidat & user di MongoDB
        MongoHelper.incrementVote(selected);
        MongoHelper.setUserVoted(currentUser.getUsername(), selected);

        // Update lokal
        currentUser.setVoted(true);
        currentUser.setVotedCandidate(selected);
        lblStatus.setText(bundle.getString("msg.vote_success"));

        // Optional: disable voting
        listCandidates.setEnabled(false);
        btnVote.setEnabled(false);

        // ✅ Kembali ke login frame
        javax.swing.JOptionPane.showMessageDialog(this, "Vote berhasil! Anda akan kembali ke halaman login.");
        this.dispose(); // tutup VotingFrame
        new LoginFrame().setVisible(true); // buka LoginFrame
    }//GEN-LAST:event_btnVoteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VotingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VotingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VotingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VotingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VotingFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVote;
    private javax.swing.JComboBox<String> cbLanguage;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JList<String> listCandidates;
    // End of variables declaration//GEN-END:variables
}
